# Generated by Django 5.2.1 on 2025-06-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('model_year', models.IntegerField(blank=True, max_length=4, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('plate', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
